- name: Demonstrates invoking our custom ansible module
  hosts: all
  ignore_errors: True
  tasks:
    - name: Invoke the hello ansible module
      hello: mesage="Hello Ansible Module!"
      register: output

    - debug: msg="Hello module invocation failed"
      when: output.failed == true 

    - debug: msg="Hello module invocation succeeded"
      when: output.failed == false 

    - name: Invoke the add ansible module
      add: firstInput=100.5 secondInput=200.5
      register: output

    - debug: msg="Result is {{output.meta}}"
      when: output.failed == false
